/* ============================================================
   TUS PROYECTOS — único archivo que necesitas editar.
   Ver paso a paso en GUIA.md
   Campos:
   - repo: nombre EXACTO del repositorio en GitHub
   - title: nombre para mostrar
   - description: 1-2 líneas (ver fórmula en GUIA.md)
   - description_en: versión en inglés (opcional, si no hay usa description)
   - tags: engine | tools | graphics | gameplay | ai | mobile
   - lang: lenguaje principal
   - gif: ruta del GIF de demostración (assets/gifs/...)
   - cover: iniciales para la portada (ej: "EN")
   - color: color de fondo de la portada
   - features: 3 puntos técnicos (metodología en GUIA.md)
   - demo: enlace opcional a demo/vídeo
   ============================================================ */
const GITHUB_USER = "AlexGuzmanSAE";

const PROJECTS = [
  {
    repo: "Cool_Eng_Repo",
    title: "Módulo de motor en C++",
    description: "Base de motor en C++: bucle principal, entidades, serialización y carga de niveles desde archivo.",
    description_en: "C++ engine foundation: main loop, entities, serialization and file-based level loading.",
    tags: ["engine", "tools"],
    lang: "C++",
    gif: "assets/gifs/cool-engine.gif",
    cover: "EN",
    color: "#1e293b",
    features: ["Bucle con paso de tiempo fijo", "Arquitectura de entidades y componentes", "Serialización y carga de niveles desde archivo"],
    demo: "",
  },
  {
    repo: "dwaRTS",
    title: "dwaRTS — RTS en C++",
    description: "Prototipo de estrategia en tiempo real en C++: selección de unidades, órdenes y cámara estratégica.",
    description_en: "Real-time strategy prototype in C++: unit selection, orders and strategic camera.",
    tags: ["engine", "gameplay", "ai"],
    lang: "C++",
    gif: "assets/gifs/dwarts.gif",
    cover: "RTS",
    color: "#134e4a",
    features: ["Selección múltiple y órdenes con clic derecho", "Máquina de estados: reposo / mover / atacar", "Cámara estratégica"],
    demo: "",
  },
  {
    repo: "ProyectoFGL",
    title: "Proyecto FGL",
    description: "Proyecto en C++ con render propio: física básica, colisiones y herramientas de depuración.",
    description_en: "C++ project with custom rendering: basic physics, collisions and debug tooling.",
    tags: ["engine", "tools", "graphics"],
    lang: "C++",
    gif: "assets/gifs/proyecto-fgl.gif",
    cover: "FGL",
    color: "#14532d",
    features: ["Render con OpenGL", "Física simple y colisiones", "Herramientas de depuración"],
    demo: "",
  },
  {
    repo: "OpenGLComGraph0",
    title: "Laboratorio OpenGL",
    description: "Prácticas de computación gráfica en C/OpenGL: pipeline, mallas, iluminación y cámara.",
    description_en: "Computer graphics coursework in C/OpenGL: pipeline, meshes, lighting and camera.",
    tags: ["graphics", "engine"],
    lang: "C",
    gif: "assets/gifs/opengl.gif",
    cover: "GL",
    color: "#1e3a8a",
    features: ["Matrices modelo-vista-proyección y shaders GLSL", "Iluminación Phong", "Cámara libre"],
    demo: "",
  },
  {
    repo: "PlatformerTemplate",
    title: "Plantilla de plataformas",
    description: "Base para prototipos de plataformas: movimiento, salto, puntos de control y niveles por tiles.",
    description_en: "Platformer starter base: movement, jumping, checkpoints and tile levels.",
    tags: ["engine", "gameplay", "tools"],
    lang: "C++",
    gif: "assets/gifs/platformer.gif",
    cover: "PT",
    color: "#0f766e",
    features: ["Controlador con respuesta ajustada", "Tiles y puntos de control", "Base reutilizable para prototipos"],
    demo: "",
  },
  {
    repo: "MooryUpCowboy",
    title: "Moory Up Cowboy",
    description: "Plataformas vertical en Unity (C#). Implementé el controlador del personaje, la progresión por niveles y el HUD.",
    description_en: "Vertical platformer in Unity (C#). Implemented the character controller, level progression and HUD.",
    tags: ["gameplay"],
    lang: "C#",
    gif: "assets/gifs/moory-up-cowboy.gif",
    cover: "MC",
    color: "#1e3a5f",
    features: ["Controlador con coyote-time y jump-buffer", "Sistema de puntuación y HUD", "Reutilización de objetos para enemigos y obstáculos"],
    demo: "",
  },
  {
    repo: "PicoGacha",
    title: "PicoGacha — Shaders y efectos",
    description: "Sistema de invocaciones con shaders personalizados y efectos visuales para rarezas.",
    description_en: "Summon system with custom shaders and visual effects for rarities.",
    tags: ["graphics"],
    lang: "ShaderLab",
    gif: "assets/gifs/pico-gacha.gif",
    cover: "PG",
    color: "#4c1d95",
    features: ["Shaders de disolución y holograma", "Sistema de rarezas con respuesta visual", "Interfaz animada"],
    demo: "",
  },
  {
    repo: "BeatEm",
    title: "Beat'em up 2D",
    description: "Juego de combate lateral: sistema de combos, oleadas de enemigos y respuesta al impacto.",
    description_en: "Side-view brawler: combo system, enemy waves and hit feedback.",
    tags: ["gameplay", "ai"],
    lang: "C++",
    gif: "assets/gifs/beatem.gif",
    cover: "BU",
    color: "#7f1d1d",
    features: ["Sistema de combos con pausa de impacto", "IA de enemigos por estados", "Aparición por oleadas"],
    demo: "",
  },
  {
    repo: "StarCloneR",
    title: "StarCloneR",
    description: "Juego de naves arcade: oleadas, patrones de enemigos, potenciadores y puntuación.",
    description_en: "Arcade space shooter: waves, enemy patterns, power-ups and scoring.",
    tags: ["gameplay"],
    lang: "C++",
    gif: "assets/gifs/starcloner.gif",
    cover: "SC",
    color: "#312e81",
    features: ["Patrones de enemigos y oleadas", "Potenciadores y puntuación", "Sistema de partículas"],
    demo: "",
  },
  {
    repo: "Bayes",
    title: "Clasificador bayesiano",
    description: "Implementación en C de un clasificador Naive Bayes, orientado a decisiones adaptativas.",
    description_en: "C implementation of a Naive Bayes classifier, aimed at adaptive decisions.",
    tags: ["ai"],
    lang: "C",
    gif: "assets/gifs/bayes.gif",
    cover: "BY",
    color: "#713f12",
    features: ["Naive Bayes desde cero", "Entrenamiento y predicción", "Aplicación a ajuste de dificultad"],
    demo: "",
  },
  {
    repo: "ML_Test",
    title: "Pruebas de ML",
    description: "Cuaderno de experimentos con modelos estadísticos, con posible aplicación a IA de juegos.",
    description_en: "Experiment notebook with statistical models, with potential game-AI applications.",
    tags: ["ai"],
    lang: "Mathematica",
    gif: "assets/gifs/ml-test.gif",
    cover: "ML",
    color: "#44403c",
    features: ["Prototipos de modelos", "Visualización de datos", "Aplicación a IA de juegos"],
    demo: "",
  },
  {
    repo: "MobilesSAE",
    title: "Proyectos móvil / web",
    description: "Prácticas de desarrollo móvil y web: interfaz táctil, diseño responsive y minijuegos HTML.",
    description_en: "Mobile and web coursework: touch UI, responsive design and HTML minigames.",
    tags: ["mobile"],
    lang: "HTML",
    gif: "assets/gifs/mobiles.gif",
    cover: "MW",
    color: "#0e7490",
    features: ["Controles táctiles", "Diseño responsive", "Compilación para móvil"],
    demo: "",
  },
];
