/* ============================================================
   AÑADE TUS REPOS AQUÍ — es el único archivo que necesitas tocar
   - repo: nombre exacto del repo en GitHub
   - title: nombre bonito para mostrar
   - description: 1-2 líneas (qué es + qué programaste tú)
   - tags: gameplay | engine | graphics | ai | mobile (para filtros)
   - lang: lenguaje principal (sale como badge)
   - gif: ruta del GIF que se ve al hacer HOVER. Súbelo a assets/gifs/
   - cover: emoji/icono de fondo mientras no hay imagen
   - features: bullets que salen en el modal (click)
   - demo: link opcional a build jugable / vídeo
   ============================================================ */
const GITHUB_USER = "AlexGuzmanSAE";

const PROJECTS = [
  {
    repo: "MooryUpCowboy",
    title: "Moory Up Cowboy",
    description: "¿Cowboy vertical? Plataformas / arcade en Unity (C#). Controllers, game feel y HUD.",
    tags: ["gameplay"],
    lang: "C#",
    gif: "assets/gifs/moory-up-cowboy.gif",
    cover: "🤠",
    gradient: "linear-gradient(135deg,#3b1d0a,#ff7a18)",
    features: ["Character controller con coyote-time y jump-buffer", "Sistema de puntuación + HUD", "Pooling de enemigos/obstáculos"],
    demo: "",
  },
  {
    repo: "dwaRTS",
    title: "dwaRTS — Mini RTS en C++",
    description: "RTS desde cero en C++. Selección de unidades, órdenes, FSM de IA y cámara estratégica.",
    tags: ["engine", "gameplay", "ai"],
    lang: "C++",
    gif: "assets/gifs/dwarts.gif",
    cover: "⚔️",
    gradient: "linear-gradient(135deg,#0a2a3b,#00e5cc)",
    features: ["Selección múltiple + click-derecho para mover/atacar", "FSM: idle / move / attack / gather", "Cámara RTS + minimapa (si aplica)"],
    demo: "",
  },
  {
    repo: "PicoGacha",
    title: "PicoGacha — Shaders & VFX",
    description: "Gacha / geo-shaders juguetones. ShaderLab + efectos para loot y summons.",
    tags: ["graphics"],
    lang: "ShaderLab",
    gif: "assets/gifs/pico-gacha.gif",
    cover: "✨",
    gradient: "linear-gradient(135deg,#2a0a3b,#ff2e88)",
    features: ["Shaders custom de disolve / holograma", "Sistema de rarezas + feedback visual", "UI animada"],
    demo: "",
  },
  {
    repo: "Cool_Eng_Repo",
    title: "Cool Engine — Módulo C++",
    description: "Experimentos de motor: bucle, ECS básico, serialización y tools.",
    tags: ["engine"],
    lang: "C++",
    gif: "assets/gifs/cool-engine.gif",
    cover: "⚙️",
    gradient: "linear-gradient(135deg,#101b3b,#8b5cff)",
    features: ["Game-loop + delta-time fijo", "Entidades / componentes", "Carga de niveles desde archivo"],
    demo: "",
  },
  {
    repo: "BeatEm",
    title: "Beat'Em — Beat'em up",
    description: "Brawler 2D: combos, hitstop, knockback y oleadas de enemigos.",
    tags: ["gameplay", "ai"],
    lang: "C++",
    gif: "assets/gifs/beatem.gif",
    cover: "🥊",
    gradient: "linear-gradient(135deg,#3b0a1a,#ff2e2e)",
    features: ["Combo system + hitstop / screen-shake", "IA de enemigos con estados", "Spawning por oleadas"],
    demo: "",
  },
  {
    repo: "ProyectoFGL",
    title: "Proyecto FGL",
    description: "Proyecto gráfico / gameplay en C++. Física básica y render propio.",
    tags: ["engine", "graphics"],
    lang: "C++",
    gif: "assets/gifs/proyecto-fgl.gif",
    cover: "🧊",
    gradient: "linear-gradient(135deg,#0a3b2a,#7dff6a)",
    features: ["Render con OpenGL / renderer propio", "Física simple + colisiones", "Debug tools"],
    demo: "",
  },
  {
    repo: "OpenGLComGraph0",
    title: "OpenGL Playground",
    description: "Laboratorio de computación gráfica: pipeline, meshes, luces y cámara en C/OpenGL.",
    tags: ["graphics"],
    lang: "C",
    gif: "assets/gifs/opengl.gif",
    cover: "🔺",
    gradient: "linear-gradient(135deg,#0a1a3b,#4da6ff)",
    features: ["Modelo MVP + shaders GLSL", "Iluminación Phong", "Cámara libre + ImGui (si aplica)"],
    demo: "",
  },
  {
    repo: "Bayes",
    title: "Bayes — IA experimental",
    description: "Clasificador bayesiano en C. Base para IA adaptativa / decisiones.",
    tags: ["ai"],
    lang: "C",
    gif: "assets/gifs/bayes.gif",
    cover: "🧠",
    gradient: "linear-gradient(135deg,#2b2b0a,#ffd11a)",
    features: ["Naive Bayes desde cero", "Entrenamiento + predicción", "Pensado para tuning de dificultad"],
    demo: "",
  },
  {
    repo: "MobilesSAE",
    title: "Mobiles — Web / Mobile",
    description: "Prácticas web-mobile: UI táctil, responsive y minijuegos HTML.",
    tags: ["mobile"],
    lang: "HTML",
    gif: "assets/gifs/mobiles.gif",
    cover: "📱",
    gradient: "linear-gradient(135deg,#1a0a2e,#00c2ff)",
    features: ["Controles táctiles", "Layouts responsive", "Builds para móvil"],
    demo: "",
  },
  {
    repo: "StarCloneR",
    title: "StarCloneR",
    description: "Clon / homenaje arcade espacial. Naves, oleadas y power-ups.",
    tags: ["gameplay"],
    lang: "C++",
    gif: "assets/gifs/starcloner.gif",
    cover: "🚀",
    gradient: "linear-gradient(135deg,#050514,#8b5cff)",
    features: ["Scroll shooter + patrones de enemigos", "Power-ups y puntuación", "Efectos de partículas"],
    demo: "",
  },
  {
    repo: "ML_Test",
    title: "ML Test",
    description: "Cuaderno de pruebas de ML (Mathematica). Para experimentar con modelos para juegos.",
    tags: ["ai"],
    lang: "Mathematica",
    gif: "assets/gifs/ml-test.gif",
    cover: "📊",
    gradient: "linear-gradient(135deg,#2a2a2a,#ff7a18)",
    features: ["Prototipos de modelos", "Visualización de datos", "Ideas para IA de juegos"],
    demo: "",
  },
  {
    repo: "PlatformerTemplate",
    title: "Platformer Template",
    description: "Template de plataformas (fork): base sólida para jams — mover, saltar, morir, repetir.",
    tags: ["gameplay", "engine"],
    lang: "C++",
    gif: "assets/gifs/platformer.gif",
    cover: "🍄",
    gradient: "linear-gradient(135deg,#0a3b3b,#00e5cc)",
    features: ["Controller con game feel", "Tiles + checkpoints", "Ideal para game jams"],
    demo: "",
  },
];
